baseURL = "https://jaredjohnson.dev"
title = "Jared Johnson"
copyright = ""
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "minimo"
enableRobotsTXT = true
enableEmoji = true
pygmentsCodefences = true

[params.info]
description = "Software makes life better"
title404 = "Not found"

[params.assets]
favicon = "favicon.ico"
customJS = ["js/index.js"]
gopher = ""

[params.copyright]
prefix = ""
holder = "Jared Johnson"
startYear = "2019"
suffix = ""

[params.settings]
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#4acaa8"
hideMainMenu = false

[params.sidebar]
enable = false

[params.seo]
titleSeparator = "|"

[params.social]
email = "jared@jaredjohnson.dev"
github = "jaredjj3"
linkedin = "www.linkedin.com/in/jaredjohnsondev"

[params.widgets]
# homepage = ["recent_posts"]
sidebar = ["about"]
footer = ["social_menu"]

[params.comments]
enable = false

[params.comments.isso]
enable = false

[params.comments.staticman]
enable = false

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "resume"
identifier = "resume"
url = "/assets/jared-johnson-resume.pdf"
weight = -100

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[deployment]
[[deployment.targets]]
name = "aws"
URL = "s3://jaredjohnson.dev?region=us-east-1"