baseURL = "http://www.jaredcodes.com"
title = "Jared Johnson"
copyright = ""
theme = "minimo"
disqusShortname = ""
googleAnalytics = ""
Paginate = 5
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt
pygmentsCodefences = true
enableEmoji = true
defaultContentLanguage = "en"

[params.info]
description = "Software makes life better"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
# customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Jared Johnson"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about"]
footer = ["social_menu"]

[params.seo]
titleSeparator = "|"

[params.social]
email = "jjohnson.eit@gmail.com"
github = "jaredjj3"
instagram = "jaredplaysguitar"
linkedin = "jjohnsoneit"

[params.comments]
enable = false

[params.comments.staticman]
enable = false

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1